In [26]:
import torch
import numpy as np

In [27]:
a = torch.tensor([1, 2])
b = torch.rand((1,2))
print(a)
print(b)
a + b

tensor([1, 2])
tensor([[0.5433, 0.4142]])


tensor([[1.5433, 2.4142]])

In [33]:
a_dub = torch.ones_like(a)
a_dub

tensor([1, 1])

In [57]:
shape = (2,3)
ones = torch.ones(shape)
print(ones.shape)
ones

torch.Size([2, 3])


tensor([[1., 1., 1.],
        [1., 1., 1.]])

## Tensor attributes
you have three att: 
* shape,
* dtype,
* device

In [ ]:
tensor = torch.rand(3,4)
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print("Device tensor is stored on: {}".format(tensor.device))

In [67]:
tensor = torch.ones(4,4)
print(tensor)
tensor[:,0] =2
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[2., 1., 1., 1.],
        [2., 1., 1., 1.],
        [2., 1., 1., 1.],
        [2., 1., 1., 1.]])


In [78]:
t1 = torch.cat((tensor, tensor, tensor), dim=1)
print(t1)

tensor([[2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1.],
        [2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1.],
        [2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1.],
        [2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1.]])


In [82]:
ones = torch.ones((2,2))
twos = 2 * torch.ones((2,2))

print(ones)
print(twos)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])


In [96]:
st = torch.stack((ones, twos),dim=2)
print(st.shape)
print(st)

torch.Size([2, 2, 2])
tensor([[[1., 2.],
         [1., 2.]],

        [[1., 2.],
         [1., 2.]]])


In [98]:
print(ones * twos)
print(ones @ twos)

tensor([[2., 2.],
        [2., 2.]])
tensor([[4., 4.],
        [4., 4.]])


In [103]:
print(tensor,"\n")
tensor.add_(5)
print(tensor)

tensor([[2., 1., 1., 1.],
        [2., 1., 1., 1.],
        [2., 1., 1., 1.],
        [2., 1., 1., 1.]]) 

tensor([[7., 6., 6., 6.],
        [7., 6., 6., 6.],
        [7., 6., 6., 6.],
        [7., 6., 6., 6.]])


In [115]:
a = np.array([[1],[2],[3]])
print(a.shape)
print(a)

(3, 1)
[[1]
 [2]
 [3]]
